name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ROM
        shell: cmd
        run: |
          build.cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: ${{ github.workspace }}/bin